# Generated by Django 3.2.20 on 2023-11-24 12:38

import logging
from django.db import migrations
from core.redis import start_job_async_or_sync

logger = logging.getLogger(__name__)

def async_index_creation(db_alias):
    from django.db import connections
    
    conn = connections[db_alias]
    
    if conn.vendor == 'postgresql':
        create_index_sql_1 = (
            'CREATE INDEX CONCURRENTLY IF NOT EXISTS task_comple_project_0bc0be_idx '
            'ON task_completion (project_id, completed_by_id);'
        )
        create_index_sql_2 = (
            'CREATE INDEX CONCURRENTLY IF NOT EXISTS task_comple_task_id_a6bdec_idx '
            'ON task_completion (task_id, id);'
        )
    elif conn.vendor == 'mysql':
        create_index_sql_1 = (
            'ALTER TABLE task_completion '
            'ADD INDEX task_comple_project_0bc0be_idx (project_id, completed_by_id), '
            'ALGORITHM=INPLACE, LOCK=NONE;'
        )
        create_index_sql_2 = (
            'ALTER TABLE task_completion '
            'ADD INDEX task_comple_task_id_a6bdec_idx (task_id, id), '
            'ALGORITHM=INPLACE, LOCK=NONE;'
        )
    else:
        logger.info(f'Database vendor: {conn.vendor}')
        logger.info('Skipping async index creation for unsupported database')
        return

    with conn.cursor() as cursor:
        cursor.execute(create_index_sql_1)
        cursor.execute(create_index_sql_2)
        logger.info('Indexes created on annotation model')

def forwards(apps, schema_editor):
    database_vendor = schema_editor.connection.vendor
    if database_vendor not in ('postgresql', 'mysql'):
        logger.info(f'Database vendor: {database_vendor}')
        logger.info('Skipping async index creation for non-PostgreSQL/MySQL databases')
        return

    # Schedule the index creation job asynchronously using RQ worker
    db_alias = schema_editor.connection.alias
    start_job_async_or_sync(async_index_creation, db_alias=db_alias)

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tasks', '0044_auto_20230907_0155'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
